version: '3.8'

services:
  expense-tracker:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount a volume to persist the SQLite database
      - expense-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: expense-tracker

volumes:
  expense-data:
    driver: local